# Generated by Django 5.0.6 on 2024-07-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
