# Generated by Django 5.0.6 on 2024-07-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_event_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='phone_num',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
