# Generated by Django 5.0.6 on 2024-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_title_event_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
